version: '3.8'

services:
  web:
    image: opc/django:latest
    command: >
      bash -c "python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               gunicorn --bind 0.0.0.0:8000 --workers 1 --worker-class sync --max-requests 1000 --max-requests-jitter 100 OPC.wsgi:application"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - db_volume:/app
    expose:
      - "8000"
    env_file:
      - .env.production
    restart: unless-stopped
    mem_limit: 512m
    memswap_limit: 1g
    shm_size: 128m
    ulimits:
      memlock:
        soft: -1
        hard: -1

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: unless-stopped
    mem_limit: 64m

volumes:
  static_volume:
  media_volume:
  db_volume:
